ccflags-y += -Wno-declaration-after-statement -Wno-implicit-fallthrough \
	-D__BIG_ENDIAN=4321 -D__LITTLE_ENDIAN=1234
obj-y += adddf3.o addsf3.o divdf3.o divsf3.o eqdf2.o eqsf2.o extendsfdf2.o \
	fixdfdi.o fixdfsi.o fixsfdi.o fixsfsi.o fixunsdfdi.o fixunsdfsi.o \
	fixunssfdi.o fixunssfsi.o floatdidf.o floatdisf.o \
	floatsidf.o floatsisf.o floatundidf.o floatundisf.o \
	floatunsidf.o floatunsisf.o gedf2.o gesf2.o ledf2.o lesf2.o \
	muldf3.o mulsf3.o negdf2.o negsf2.o subdf3.o subsf3.o \
	truncdfsf2.o unorddf2.o unordsf2.o
