/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#undef HAVE_COPY_FILE_RANGE

#undef HAVE_FALLOCATE

#define HAVE_FDATASYNC

#undef HAVE_FORK

#define HAVE_FSTATAT

#define HAVE_ICONV

#define HAVE_OPENAT

#undef HAVE_PIPE2

#define HAVE_POSIX_FALLOCATE

#define HAVE_READLINKAT

#undef HAVE_SETXATTR

#undef HAVE_SPLICE

#define HAVE_STRUCT_STAT_ST_ATIM

#undef HAVE_STRUCT_STAT_ST_ATIMESPEC

#define HAVE_UTIMENSAT

#undef HAVE_VMSPLICE

#define PACKAGE_VERSION "3.16.1"

